{
 "title": "AD Monitoring",
 "tags": [ "ad" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Domain controller",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Создана УЗ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Windows Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Windows Security (ID4720)" },
     "itemTag": { "filter": "Application: Security events" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 1,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "history",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "textFilter": ".",
     "trigger": { "filter": "User locked" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 1
     }
    }
   ]
  },
  {
   "title": "Включена УЗ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Windows Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Windows Security (ID4722)" },
     "itemTag": { "filter": "Application: Security events" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 1,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "history",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "textFilter": ".",
     "trigger": { "filter": "User locked" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 1
     }
    }
   ]
  },
  {
   "title": "Разблокирована УЗ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Windows Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Windows Security (ID4767)" },
     "itemTag": { "filter": "Application: Security events" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 1,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "history",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "textFilter": ".",
     "trigger": { "filter": "User locked" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 1
     }
    }
   ]
  },
  {
   "title": "Изменена УЗ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Windows Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Windows Security (ID4738)" },
     "itemTag": { "filter": "Application: Security events" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 1,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "history",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "textFilter": ".",
     "trigger": { "filter": "User locked" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 1
     }
    }
   ]
  },
  {
   "title": "Распределение событий по времени",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Windows Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "Application: Security events" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 1,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "history",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "textFilter": ".",
     "trigger": { "filter": "User locked" },
     "triggers": {
      "acknowledged": 2,
      "count": false
     }
    }
   ]
  },
  {
   "title": "Удалена УЗ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Windows Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Windows Security (ID4726)" },
     "itemTag": { "filter": "Application: Security events" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 1,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "history",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "textFilter": ".",
     "trigger": { "filter": "User locked" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 1
     }
    }
   ]
  },
  {
   "title": "Отключена УЗ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Windows Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Windows Security (ID4725)" },
     "itemTag": { "filter": "Application: Security events" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 1,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "history",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "textFilter": ".",
     "trigger": { "filter": "User locked" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 1
     }
    }
   ]
  },
  {
   "title": "Заблокирована УЗ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Windows Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Windows Security (ID4740)" },
     "itemTag": { "filter": "Application: Security events" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 1,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "history",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "textFilter": ".",
     "trigger": { "filter": "User locked" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 1
     }
    }
   ]
  },
  {
   "title": "Сброс пароля",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Windows Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "Windows Security (ID4724)" },
     "itemTag": { "filter": "Application: Security events" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 1,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "history",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "textFilter": ".",
     "trigger": { "filter": "User locked" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 1
     }
    }
   ]
  },
  {
   "title": "Поиск по событиям",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 47, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Windows Servers" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "Application: Security events" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": true,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": true,
      "sortProblems": "default",
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "slaInterval": "none",
     "slaProperty": "sla",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  }
 ]
}