{
 "title": "HTTP Response",
 "tags": [ "web" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "URL https://",
    "query": "b2b.smpins.ru, b2b.psbins.ru, smpins.ru,  psbins.ru,  family.smpins.ru, family.psbins.ru, lk.smpins.ru, lk.psbins.ru, portal.smpins.ru, portal.psbins.ru, post.smpins.ru, post.psbins.ru, RSA-KaskoService, monitoring.psbins.ru, bearpass.interinscom.ru"
   }
  ]
 },
 "panels": [
  {
   "title": "Response time ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "rtt",
     "application": { "filter": "" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "zabbix-server" },
     "item": {
      "filter": "Response time for step \"index\" of scenario \"$hostname\"."
     },
     "itemTag": { "filter": "" },
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "type:collectd AND plugin:ping AND hostname:\"$hostname\" AND collectd_type:ping",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "timeField": "@timestamp",
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Response code",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "zabbix-server" },
     "item": {
      "filter": "Response code for step \"index\" of scenario \"$hostname\"."
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "stddev",
     "application": { "filter": "" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "zabbix-server" },
     "item": {
      "filter": "Download speed for scenario \"$hostname\"."
     },
     "itemTag": { "filter": "" },
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "type:collectd AND plugin:ping AND hostname:\"$hostname\" AND collectd_type:ping_stddev",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "timeField": "@timestamp",
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "zabbix-server" },
     "item": {
      "filter": "Failed step of scenario \"$hostname\"."
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Result Code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "droprate",
     "application": { "filter": "" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "zabbix-server" },
     "item": {
      "filter": "Failed step of scenario \"$hostname\"."
     },
     "itemTag": { "filter": "" },
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "type:collectd AND plugin:ping AND hostname:\"$hostname\" AND collectd_type:ping_droprate",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "timeField": "@timestamp",
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Response code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "alias": "droprate",
     "application": { "filter": "" },
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "zabbix-server" },
     "item": {
      "filter": "Response code for step \"index\" of scenario \"$hostname\"."
     },
     "itemTag": { "filter": "" },
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "type:collectd AND plugin:ping AND hostname:\"$hostname\" AND collectd_type:ping_droprate",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "timeField": "@timestamp",
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}