{
 "title": "Squid Log Monitoring",
 "tags": [ "squid" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Proxy",
    "label": "Proxy name",
    "query": "{\"find\": \"terms\", \"field\":\"source\" }"
   },
   {
    "name": "user",
    "label": "User",
    "query": "{\"find\": \"terms\", \"field\":\"User\",\"size\": \"1000\" }"
   },
   { "name": "sites", "label": "Sites (all sites: *)", "query": "*" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "General Analisys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "Bytes",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "source:$Proxy AND User:$user AND (Method:CONNECT OR Method:GET OR Method:POST) AND NOT Result_Code:\"TCP_DENIED\" AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Bytes",
       "hide": false,
       "id": "1",
       "settings": { "script": "_value/1024/1024" },
       "type": "sum"
      }
     ],
     "query": "source:$Proxy AND User:$user AND (Method:CONNECT OR Method:GET OR Method:POST) AND NOT Result_Code:\"TCP_DENIED\" AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top User Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Bytes",
       "hide": false,
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "source:$Proxy AND User:$user AND NOT Result_Code:\"TCP_DENIED\"  AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "source:$Proxy AND User:$user AND (Method:CONNECT OR Method:GET OR Method:POST) AND NOT Result_Code:\"TCP_DENIED\"  AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Visited Site",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "URI_Host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      },
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source:$Proxy AND User:$user AND NOT Result_Code:\"TCP_DENIED\" AND NOT URI_HOST:\"ocsp.int-x3.letsencrypt.org\"  AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hits of Users",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source:$Proxy AND User:$user AND NOT Result_Code:\"TCP_DENIED\"  AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Traffic by User",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "Bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "source:$Proxy AND User:$user AND NOT Result_Code:\"TCP_DENIED\" AND (Method:CONNECT OR Method:GET OR Method:POST)  AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Access",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "URI_Host",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source:$Proxy AND User:$user  AND NOT Result_Code:\"TCP_DENIED\"  AND NOT URI_HOST:\"ocsp.int-x3.letsencrypt.org\"  AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Access Denied",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "URI_Host",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source:$Proxy AND source:$Proxy AND User:$user  AND Result_Code:\"TCP_DENIED\"  AND NOT URI_HOST:\"ocsp.int-x3.letsencrypt.org\"  AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Squid Codes",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "Result_Code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source:$Proxy AND User:$user  AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Proxy server",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source:$Proxy AND User:$user  AND (URI_Host:$sites or $sites:*)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Sites",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "URI_Host",
         "id": "12",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" },
        {
         "field": "Bytes",
         "id": "9",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "Duration",
         "id": "11",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "source:$Proxy AND User:$user AND (Method:CONNECT OR Method:GET OR Method:POST) AND NOT Result_Code:\"TCP_DENIED\" AND (URI_Host:$sites or $sites:*)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Sites by users",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "timestamp",
         "id": "13",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "Client_Address",
         "id": "14",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "User",
         "id": "15",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "URI",
         "id": "16",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "source",
         "id": "17",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "source:$Proxy AND User:$user AND (Method:CONNECT OR Method:GET OR Method:POST) AND NOT Result_Code:\"TCP_DENIED\" AND (URI_Host:$sites or $sites:*)",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}