{
 "title": "VPN Connections Users",
 "tags": [ "net" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {}
   },
   {
    "name": "User",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Accumulated VPN Connections Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Network devices" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Oper/" },
     "itemTag": { "filter": "$User" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": true,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "false",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "~ Output traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "8" ],
       "text": "scale(100)"
      }
     ],
     "group": { "filter": "Network devices" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Bits sent.*/" },
     "itemTag": { "filter": "$User" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "false",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "~ Input traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "8" ],
       "text": "scale(100)"
      }
     ],
     "group": { "filter": "Network devices" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Bits received.*/" },
     "itemTag": { "filter": "$User" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "false",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": " VPN Connections Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Network devices" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Oper/" },
     "itemTag": { "filter": "$User" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "VPN Connections Time per day",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "24h",
        "count"
       ],
       "text": "groupBy(1m, avg)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "123" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "Network devices" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Oper/" },
     "itemTag": { "filter": "$User" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": true,
      "minSeverity": 3,
      "showDisabledItems": true,
      "skipEmptyValues": false,
      "useTrends": "false",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Bits sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Network devices" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Bits sent.*/" },
     "itemTag": { "filter": "$User" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Bits received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Network devices" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Bits received.*/" },
     "itemTag": { "filter": "$User" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  }
 ]
}